<?php

namespace JansenFelipe\SintegraPHP\Tipos;

class ModeloNF {

    const AUTORIZACAO_CARREGAMENTO_TRANSPORTE = 24;
    const BILHETE_PASSAGEM_AQUAVIARIO = 14;
    const BILHETE_PASSAGEM_FERROVIARIO = 16;
    const BILHETE_PASSAGEM_NOTA_BAGAGEM = 15;
    const BILHETE_PASSAGEM_RODOVIARIO = 13;
    const CONHECIMENTO_AEREO = 10;
    const CONHECIMENTO_TRANSPORTE_AQUAVIARIO_CARGAS = 9;
    const CONHECIMENTO_TRANSPORTE_ELETRONICO = 57;
    const CONHECIMENTO_TRANSPORTE_FERROVIARIO_CARGAS = 11;
    const CONHECIMENTO_TRANSPORTE_MULTIMODAL_CARGAS = 26;
    const CONHECIMENTO_TRANSPORTE_RODOVIARIO_CARGAS = 8;
    const DESPACHO_TRANSPORTE = 17;
    const MANIFESTO_DE_CARGA = 25;
    const NOTA_FISCAL = 1;
    const NOTA_FISCAL_ELETRONICA = 55;
    const NOTA_FISCAL_ENERGIA_ELETRICA = 6;
    const NOTA_FISCAL_ENTRADA = 3;
    const NOTA_FISCAL_PRODUTOR = 4;
    const NOTA_FISCAL_SERVICO_COMUNICACAO = 21;
    const NOTA_FISCAL_SERVICO_TELECOMUNICACAO = 22;
    const NOTA_FISCAL_SERVICO_TRANSPORTE = 7;
    const NOTA_FISCAL_SERVICO_TRANSPORTE_FERROVIARIO = 27;
    const NOTA_FISCAL_VENDA_CONSUMIDOR = 2;
    const ORDEM_COLETA_CARGA = 20;
    const RESUMO_MOVIMENTO_DIARIO = 18;

}
